import React from 'react';
import { formatDate } from '@/lib/utils';
import { CrewMemberWithDetails } from '@shared/schema';

interface PrintableCrewListProps {
    crewMembers: CrewMemberWithDetails[];
    categoryName: string;
}

export const PrintableCrewList = React.forwardRef<HTMLDivElement, PrintableCrewListProps>(({ crewMembers, categoryName }, ref) => {
    if (!crewMembers || crewMembers.length === 0) return null;

    return (
        <div ref={ref} className="p-8 bg-white text-gray-900 font-sans min-h-[297mm] w-full">
            <div className="border-b-2 border-slate-800 pb-4 mb-8">
                <div className="flex justify-between items-end">
                    <div>
                        <h1 className="text-2xl font-bold uppercase tracking-widest text-[#1E293B]">Crew Report</h1>
                        <p className="text-xs text-slate-500 font-bold uppercase tracking-tight mt-1">Category: {categoryName}</p>
                    </div>
                    <div className="text-right">
                        <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest leading-none mb-1">Generated by SeaCrew Manager</p>
                        <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest leading-none">Date: {new Date().toLocaleDateString('en-GB')}</p>
                    </div>
                </div>
            </div>

            <table className="w-full border-collapse">
                <thead>
                    <tr className="border-b-2 border-slate-700 bg-slate-50">
                        <th className="py-2.5 px-3 text-left text-[10px] font-extrabold text-slate-500 uppercase tracking-widest w-[10%]">S/N</th>
                        <th className="py-2.5 px-3 text-left text-[10px] font-extrabold text-slate-500 uppercase tracking-widest w-[25%]">Vessel Name</th>
                        <th className="py-2.5 px-3 text-left text-[10px] font-extrabold text-slate-500 uppercase tracking-widest w-[35%]">Crew Name</th>
                        <th className="py-2.5 px-3 text-left text-[10px] font-extrabold text-slate-500 uppercase tracking-widest w-[15%]">Sign On</th>
                        <th className="py-2.5 px-3 text-left text-[10px] font-extrabold text-slate-500 uppercase tracking-widest w-[15%]">Sign Off</th>
                    </tr>
                </thead>
                <tbody>
                    {crewMembers.map((member, index) => (
                        <tr key={member.id} className="border-b border-slate-150 last:border-0">
                            <td className="py-3 px-3 text-[11px] font-bold text-slate-400">{index + 1}</td>
                            <td className="py-3 px-3 text-xs font-bold text-[#1E293B] uppercase">{member.currentVessel?.name || 'N/A'}</td>
                            <td className="py-3 px-3 text-xs font-bold text-[#1E293B] uppercase">{member.firstName} {member.lastName}</td>
                            <td className="py-3 px-3 text-xs font-bold text-slate-700">{member.activeContract?.startDate ? formatDate(member.activeContract.startDate) : 'N/A'}</td>
                            <td className="py-3 px-3 text-xs font-bold text-slate-700">{member.activeContract?.endDate ? formatDate(member.activeContract.endDate) : 'N/A'}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <div className="mt-20 pt-8 border-t border-slate-100 flex justify-between items-center text-[9px] text-slate-400 font-bold uppercase tracking-widest">
                <span>Marine Operations Official Documentation</span>
                <span>Total Seafarers: {crewMembers.length}</span>
            </div>

            <div className="mt-4 text-center text-[7px] text-slate-300 italic">
                This report is electronically generated and holds validity as per company policy. Page 1 of 1
            </div>
        </div>
    );
});

PrintableCrewList.displayName = 'PrintableCrewList';
